### PR TITLE
[Bug] Fix the state compatibility problem

### LINKED ISSUE #256: [Bug] Job can not restore from checkpoint/savepoint after doris connector upgrade to 1.5.0
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.5.0

### What's Wrong?

Job can not restore from checkpoint/savepoint after doris connector upgrade to 1.5.0

### What You Expected?

Fix the state compatibility problem.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tan-JiaLiang**
# Proposed changes

Issue Number: close #256

## Problem Summary:

#224 Made a change to DorisWriterState without considering connector state compatibility, resulting in an upgrade to 1.5.0 error, So I wana to fix this.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java [hunk 1]
```diff
@@ -130,6 +130,9 @@ private void abortLingeringTransactions(Collection<DorisWriterState> recoveredSt
              if(!state.getLabelPrefix().equals(labelPrefix)){
                  LOG.warn("Label prefix from previous execution {} has changed to {}.", state.getLabelPrefix(), executionOptions.getLabelPrefix());
              }
+             if (state.getDatabase() == null || state.getTable() == null) {
+                 continue;
```
Comment (JNSimba) [inline flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java:134]: Thank you for your contribution. Would it be better to add some logs here to inform users that the historical state cannot be aborted?

**Comment by Tan-JiaLiang** [comment]
@JNSimba Thanks for your help with code review, would you mind taking another look?

**Review by JNSimba — APPROVED** [review]
LGTM
